export default {
  '@chengdx/shared': [
    'capitalize',
    'charMatches',
    'createArray',
    'createHandlers',
    'formatNaming',
    'indexOfFirstLetter',
    'indexOfFirstMacthes',
    'isLetter',
    'isLowerCase',
    'isNumber',
    'isSpecial',
    'isUpperCase',
    'match',
    'matchEvery',
    'matchSome',
    'replaceSubstring',
    'resolveArray',
    'resolveCallable',
  ],
}
